#!/bin/sh
if test "$#" = 2; then
    xmllint --format  $1 > $2;
elif test "$#" = 1; then
    xmllint --format  $1 > $1.tmp;
    rm $1;
    mv $1.tmp $1;
else 
    echo "  Expected 1-2 args [current file] {name of new file}, got $#."
fi
