# h = show bash helper commands (e.g., go fn, ma)

# convenience commands
alias c='clear'
alias duh='du -lh --max-depth=1'
alias d0='du -lh --max-depth=0'
alias t='tmux'
alias e='exit'
alias f='find . -iname'
alias p='plantuml'
alias gol='go -l'
alias psg="ps -x | grep -v grep | grep -i"
alias tview='tar -ztvf'
alias tarchive='tar -cvzf'
alias textract='tar -xvzf'

# ls
alias l='ls -1'
alias la='ls -l -A'
alias ll='ls -1 -A | less'
alias lsg='ls | grep'
alias ag='grep -rnw . -e'

#git
alias gf="git fetch --all --prune"
alias gp="git pull"
alias gph="git push origin HEAD"
alias gphf="git push origin HEAD --force-with-lease"
alias g="git status"
alias gc="git commit -m"
alias gca="git commit --amend"
alias ga="git add -A"
alias gmt="git mergetool"
alias gcfd="git clean -fd"
alias grc="git rebase --continue"
alias gback="git reset --hard HEAD"
alias gundo="git reset --hard HEAD~1"
alias gl="git log --graph --oneline --all -n 20"
alias glm="git log --graph --oneline -n 20"
alias gll="git log --graph --oneline --all -n 50"
alias gla="git log --graph --oneline --all"
alias gd="git diff -w"
alias gb="git branch"
alias gdel="git branch -D"
alias gco="git checkout"
alias gri="git rebase -i"
alias gdl="git diff HEAD~"

#settings
alias bu="source ~/.zshrc"
alias ea="vim ~/.bash_aliases"
alias ef="vim ~/.bash_functions"
alias er="vim ~/.zshrc"
alias ma="less ~/.bash_aliases"
alias mf="less ~/.bash_functions"
alias mr="less ~/.zshrc"

#gradle
alias gcb="./gradlew clean ktlintFormat build"
alias gcbs="./gradlew clean ktlintFormat build -x test"
alias gcbs="./gradlew clean ktlintFormat build -x test"
alias gkt="./gradlew ktlintFormat"
alias gta="./gradlew tasks"

# docker
alias dps="docker ps --format \"{{.ID}} {{.Names}}\""
alias dpsit="docker ps --format \"{{.ID}} {{.Names}}\" | grep"
alias dis="docker inspect"
alias dlo="docker logs"
alias dcu="docker-compose up"
alias dlf="docker logs --follow"
alias dmi="docker images"
alias drmi="docker rmi"
alias dstop="docker stop"
alias drm="docker rm"

# aws
alias aprof="echo $AWS_PROFILE"

# git & maven documentary
# alias guntrack="git update-index --assume-unchanged"
# alias gretrack="git update-index --no-assume-unchanged"
# alias mcip="mvn clean install -pl"
# alias mrel="mvn release:prepare -DautoVersionSubmodules=true -DpushChanges=false"

# maven
alias mci="mvn clean install"
alias mcio="mvn clean install -o"
alias mcis="mvn clean install -DskipTests"
alias mcc="mvn clean compile"
alias mut="mvn clean compile surefire:test"
alias mit="mvn clean compile failsafe:integration-test"
alias mtest="mvn test -PskipDependencyCheck -Dtest=*$*"
alias mdt="mvn dependency:tree"
